# site settings
title: HeroBuxx
subtitle:
email: me@herobuxx.xyz
description: HeroBuxx's GitHub Page.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: HeroBuxx
street_address: Sungai tanang
city: Agam
state:
zip_code: 26181
country: Indonesia
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/herobuxx
googleplus_url:
instagram_url: https://instagram.com/rev31one
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/iamHeroBuxx

# build settings
markdown: kramdown

sass:
  style: compressed
